#!/bin/sh
# Fixing misbehaving Java Applications (https://wiki.archlinux.org/index.php/Dwm#Fixing_misbehaving_Java_applications)
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_FX_WM_NONREPARENTING=1

# gtk theme for qt
export QT_QPA_PLATFORMTHEME=gtk2

# ADD $HOME/.local/bin TO PATH
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':')"

# DBUS
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u $USER)/bus"

# SET PROGS
export FILE="lf"
export EDITOR="/usr/bin/nvim"
export TERMINAL="/usr/local/bin/st"
export MUSIC="/usr/bin/ncmpcpp"
export BROWSER="/usr/bin/brave-browser"
# export BROWSER="/usr/bin/qutebrowser"
export READER="/usr/bin/zathura"
export MULTIPLEX="tmux"
export MANPAGER='nvim +Man!'

# $HOME CLEAN-UP
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$HOME/.config/zsh"
export WGETRC="$HOME/.config/wget/wgetrc"
export GOPATH="$HOME/.local/share/go"
export CARGO_HOME="$HOME/.local/share/cargo"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export GNUPGHOME="${XDG_CONFIG_HOME:-$HOME/.config}/gnupg"

# LESS
export LESSHISTFILE="-"
export LESS=-R
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;30m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;34m'
export LESS_TERMCAP_ue=$'\e[0m'

# FFF
export FFF_FILE_FORMAT=" %f"
export FFF_MARK_FORMAT="> %f"
export FFF_OPENER="lf_opener"

# GREP
export GREP_COLORS="fn=34:mt=01;34:ln=01;30:se=30"

# SUDO PROMPT
export SUDO_PROMPT=$(printf "\e[01;30;47msudo\e[0m : ")

eval $(dircolors $HOME/.config/dir_colors)

LF_ICONS=$(sed ~/.config/icons \
            -e '/^[ \t]*#/d'       \
            -e '/^[ \t]*$/d'       \
            -e 's/[ \t]\+/=/g'     \
            -e 's/$/ /')
LF_ICONS=${LF_ICONS//$'\n'/:}
export LF_ICONS

# START WM WITH LOGIN
# exec startx
